### ISSUE TITLE
Error: Could not find or load main class sample.Main Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

### ISSUE THREAD

**Issue by m-a-prod** [IgorTimofeev/OCIFImageConverter#6]

**Comment by BenDizer** [comment]
Missing javaFX module which was removed in new versions of java. I added the necessary modules and a script to launch https://disk.yandex.ru/d/SDAuf-ybRgrdMw

**Comment by m-a-prod** [comment]
Так вот че эта прога не запускалась

**Comment by YourDLCMaster** [comment]
> Missing javaFX module which was removed in new versions of java. I added the necessary modules and a script to launch https://disk.yandex.ru/d/SDAuf-ybRgrdMw

The Yandex link doesn't work for me. If someone could provide the file attached that would be much appreciated.

**Comment by BenDizer** [comment]
Hello, uploaded for you on mega https://mega.nz/file/flslgArT#jyyxM1UfurQ8KZgcPssg0Baddm-Loc3GPRTtN7f5f7k[Mega]

**Comment by m-a-prod** [comment]
Cool

**Comment by MrPixel92** [comment]
> Missing javaFX module which was removed in new versions of java. I added the necessary modules and a script to launch https://disk.yandex.ru/d/SDAuf-ybRgrdMw

**Comment by MrPixel92** [comment]
> Missing javaFX module which was removed in new versions of java. I added the necessary modules and a script to launch https://disk.yandex.ru/d/SDAuf-ybRgrdMw

Б***ь, нах** ты ZIP-бомбу в архив положил???

Прошу прощения, видимо что-то неверно скачалось. Просто до этого при распаковке система зависала а после остановки получался start.bat в 49 ГБ.

**Comment by YourDLCMaster** [comment]
> Hello, uploaded for you on mega [https://mega.nz/file/flslgArT#jyyxM1UfurQ8KZgcPssg0Baddm-Loc3GPRTtN7f5f7k[Mega]](https://mega.nz/file/flslgArT#jyyxM1UfurQ8KZgcPssg0Baddm-Loc3GPRTtN7f5f7k%5BMega%5D)

Thank you very much!

**Comment by LeGamermc** [comment]
wont run on linux:
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:410)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1082)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1082)
Caused by: java.lang.RuntimeException: No toolkit found
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:410)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
	... 5 more

**Comment by ke46138** [comment]
### Туториал по запуску на linux:

> [!WARNING]
> Работает только в x11 или в Xwayland

1. Скачиваем java (если не установлена)
2. Скачиваем это: [тыкъ](https://disk.yandex.ru/d/YkoMnM7OnwShCw) или если не работает, то [тыкъ](https://www.dropbox.com/scl/fi/1dlegxkbldcapjfdmylen/ocif.tar.gz?rlkey=pie17e75luxyyzyvmjivj660q&st=22145fk1&dl=0)
3. Распаковываем командой `tar -xvf ocif.tar.gz`
4. `cd converter_ocif`
5. `./start.sh`

Программу взял [отсюда](https://disk.yandex.ru/d/SDAuf-ybRgrdMw) и добавил туда javafx для linux 64 bit.

Проверено в Arch Linux
